[package]
name = "froovie_front"
version = "0.1.0"
authors = ["okno <paul.delafosse@protonmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
serde = "1"
serde_derive = "1"
stdweb = "0.4"
yew = "0.6.0"
log = "0.4"
